config:
  batch_size: 32
  data_paths:
  - test_datasets/shehata/fragments/VH_only_shehata.csv
  device: mps
  label_column: label
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc
  - pr_auc
  model_paths:
  - models/boughter_vh_esm2_650m_logreg.pkl
  output_dir: ./test_results
  save_predictions: true
  sequence_column: sequence
dataset: VH_only_shehata
model: boughter_vh_esm2_650m_logreg
results:
  classification_report:
    '0':
      f1-score: 0.585278276481149
      precision: 0.9819277108433735
      recall: 0.41687979539641945
      support: 391.0
    '1':
      f1-score: 0.03347280334728033
      precision: 0.017241379310344827
      recall: 0.5714285714285714
      support: 7.0
    accuracy: 0.41959798994974873
    macro avg:
      f1-score: 0.3093755399142147
      precision: 0.4995845450768592
      recall: 0.4941541834124954
      support: 398.0
    weighted avg:
      f1-score: 0.5755731550943725
      precision: 0.9649608658164108
      recall: 0.41959798994974873
      support: 398.0
  confusion_matrix: !!python/object/apply:numpy._core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 2
      - 2
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      owAAAAAAAADkAAAAAAAAAAMAAAAAAAAABAAAAAAAAAA=
  predictions:
    y_pred: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 398
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
        AAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAA
        AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
        AAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA
        AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA
        AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAA
        AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
        AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA
        AQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAB
        AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAA
        AAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA
        AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA
        AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
        AAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAA
        AAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAA
        AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAA
        AAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB
        AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAA
        AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAA
        AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
        AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA
        AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA
        AAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA
        AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAA
        AAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB
        AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEA
        AAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAA
        AAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
        AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAA
        AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAA
        AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==
    y_proba: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 398
      - !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        1YPZLDZn3j+/10HvBO3XP783Lu7vytY/vKoUETU74z/y9ZEnPeniP5n9rlPiU+M/Np+QoqQTzj+8
        ix8/X+TZPwlPdndR/+A/spaAYT8tzz87rMG0O27lPy2aArlLotw/UHdfp5hX5D8R6HAB0I7ZP9xT
        XCz5kt4/3x5XQCCb6j852roQINbdPzJDbMPIe94/7LFOWgox4z+QHEKshHXVPy2+7cHNAuE/MiH6
        hUGT1j/MgA5zaRTdP/DoUzNuquY/xp+p1b9Z3D+5JQGmAEPXP82iUArVZOA/ouhymvPO5D/of/WD
        Ex7ZP56omrVz9tI/DZXVEq8f3j9F8VvfNP/QP+z1aC6Azts/v5lW/RE12j/oVetTiVnjP8s4PBGQ
        Nts/7NRa3j965D9VjszRWVPgPzZSFPbs6+I/C9zlbMqh3T92BG51QobhPzhx1JUgzeA/rnRyJoUI
        3T9ihlbJXmXgP6ie4J+i9tQ/auf5ZBvz3j+gSGXfZubhP/ouMFXGJuY/NOkcGjzG5D+APLBCNrHc
        P1KsxrMkw+E/Mxxk4fhg4z+C9TUS1y3bPwTeHQatw+Q/R7e2qPnJ2z/DhAHrZDTgPyiZSaLhmOQ/
        A4lH30C84D/9JAc+bxjfPztwfM0UE8k/wo2KgRcs5j+tY5AeqkjUPxBb/uo9jeE/xmqo7sI64T++
        CYVa+IPfP0UsGjyM5uo/4r7013lM4T9dqttI3nLgP0EVW82REOU/yFC1XXYX4j8x+lEfbgPfP6vJ
        STQxouE/tKiV9UdW5D9axT34D2/RP4fKiSnJ4+Q/2OzVOL4Q5z+4gBtK/VviP+woITy/kts/JTnO
        FUt35j+ft2nMX+HfPwrcyJPP3NA/gSJFc2RI5T9J9wN7bTLjPzXJtHb2HOE/ZMujULTZ5j+WO6s+
        O7jmPwQEMqrWPdg/8/8YSSD3zz+CYkoEZqzlPwNJuxQ3/+U/u14JHPSP4j/svIoHGhvlPwbLfZn5
        g+Q/Y5YuwESi0z/RwxR1ydnrPwwMbszFrN0/0DJyI6QB3D801L86ZI3hP9q+w+FQeuU/nd8e5BPj
        5j+webchXPfZP7DBi6tMLt8/qi291H2j3z8F+8eL0mDrP1w3J4yUQuU/urxX9aBh4T9zcFac/zXT
        P3wFzWvOPOI/qGYuOe2L4j/7hNun+y3jPzF0q4lb8tk/YAbf4XQJ5z8QgV9z2KPoP12kom1zwOY/
        MXH3QUMb4j/exMR80sTgP894Ifl8W+U/ataf9m7g4D8FlWDg4BnfP5LSq6WEzt0/j1VPAoLz4D8V
        RztKR5XhP3IPszsFQuQ/fN7kf+Bx4j9f5meMN4vbP0aTOrr7Vdo/Cbzte90V0z/YSXJ9NZHiP+ku
        Q6P9heM/LYGI1g+65z+MmIEETgXbPwKyyPpmjdw/LiZI1+D35D9/J6M0tyLhP1zzxfszztw/DJqz
        +K8H5z+rqYR8KlbjPw+ir77H+uI/qMbz5phr1j/NwRDstC/gP+UDD3MANOM/juOuxc4l2D8Llv6T
        TyrpPznJ3+W6iuU/Pc6WXNrk4T911Z4fFiLpP3ka8KKhieE/fBJFQ2ES3D/hcv3rTejfP9eTwJG1
        IOU/c26AQdBh0j8Hooqe/83YP3IhVWQ3Ito/JtqrbcNf4D8+2jiIPo/gP6GuC67JkdA/4krUrF/H
        1j+rPlkbQPrlPz/Yw/KfmuE/b4puJxyV1j8BFEXKmprgP7CAdQdMRNk/QHpvx4QW3D/IxjndVATV
        P8XXd0D2a9Q/I0EBKJrG2z8JzorIRB7iP8yICxSSUuY/uEwB2sHI3z/Gedwg1DLgP+K34WenXOM/
        YBFDnu286D91EvYERIjZP8/wmxtXzuA/VKQQDJlI4z+hfKVQdQfhPwQh9kyjquY/iFLwWX5I1T9C
        awrkQbraP2GZKn3LwuA/kaNe2jz64T9VBLoBobfXP3nLkrzscOU/F/lGK9sW1j+cgZLhB4DZP3vk
        5HxMSeQ/YB5REBFx5T9g2Syr1ZDiPw6/9ve+JOU/VL7jWHxI2z/ovLnI/v/YPwdlHAc91+M/1RlL
        hMXE2z+DEIinsS7aPykSnjPmx+E/2LyAORk43T+NeiyHbeDkP9OaWBxgqOI/FSaM38OO4T8Z9MMS
        6PrkPxe9gfXs/OI/qEbfPXto2D/qswpHTnzkP5PPuumJGOE//JecTaLC4T9VVk3zeZ7lP3X+Kljy
        wt4/Djs9lU/Q6D+Mx42nOoDZP8MFFCt8tNo/5wnXydml4D/lnWF/xHnmP5FLACnpDOc/d5Ds8D7c
        5T+WdKa+YkbhPxKNUXrQ/OY/A9FMfK+51T+Eh2UJXhjbP4z420vJ/NU/hJ5J1vrW2z+VfkXOOgfc
        Px9tqx/vDug/sghUrPgr3D8qnmRkVKjiP1LwVmzUMtk/icLUXBq03j+E1z4TYJ3eP6tx3EW5etU/
        qDe202x63j9I1Tg7a4PhP+llf/QMTtg/aggJzO5S1z9O6h2x2a/dP/fVxzacG94/QZhbp+wm3z+0
        /aKCstnjP5PL+648Z+g/xmvMDwrR6D8fnqIm8mPUPz+6lZMhRt4//UC+wTbP4T9ksVsJB1HiP4PV
        IyKKztc/+lQuJdr34j9dItmrXCTdPwHmlJvK7d8/HExSD0RW3T8VM4ld1zTiP7pIUurDZtE/JU6M
        cIUt4j+yfuXN0d/TP7snRrR8MN4/HOvNYTLl1z9itmElnjThP0xOzKNAVeE/WRdvdWya4D+NWVt/
        AhzjP8noWAsTBNA/7HPQWfNh1D/F22OQYX/aP8bC5APtCeI/Baf7UoUd4D/3kiYbpl3jP2Nq3MZ2
        wuk/3yiBsTxJ5D9aMHlbOSbSP4FN9VMyRdo/yEH1Mw2J4T+gV9HA4IraP/Uydk1qI9o/5n02kYkl
        2z8RfMlQhh3iPyExxvbXL+Y/yBq/lEuu5T/crRMNPJbSP/y8J0O6H+E/3eRKlwXV5z++CtcmsL/g
        Py+POqPkV+A/u5JQ73Hq5j82IVRYwlLmPzuEyiFT7+c/l8R4TpbC5z9KPpFYI/LqP9VuKb3HSds/
        o9DN/2Ur5T+rsZ+getDXP1JPw7BaWeI/uqPPJ3Ug4D8Tha+66ZTjPxYwsRIfVuI/b3CiX2a84z/k
        8eaXhfLbPxvP73w+muY/nSTMJcgd5z+AiaiXzdvhP81rse2K1eM/xmkGdcNY5T+aP8gBGFTdP7f/
        0kgDdt0/pKMI49w84z9PPZCFrGrnPy4DeG0iZus/B+vGYx+y3z+BDt6aqRbQP2Ol72obMuQ/g74L
        92236D90p8vtXOHgP/gtZkyGVuI/+1JbFBEL6D8u9zZVn9XiP204qc6mD+M/W6ADLgId2T+2tQwl
        OCHhP98UXY7t7uc/I1n0Szem5j+QPOXB6H7pPwBMMqNOl98/QhsryL9t5T+UzxdVym3iP24cQ5om
        rOU/+k/ZGyBo1D/UpU8TkZXkP/gCRM8fM+Q/6GLOz8R15T+nHEHHiozgP0YhHbRMl9k/H23iwM9N
        4j+rNqzcrmvUP2MXIau3Pd8/9ZXjcGbL2D9qD+yhTfPnP1nV8cGEZNk/TbtI84t72z+/lWiD3eXe
        PyQMYmBM9OE/VZ3OUvbu2j/P31Kg3n3eP3pC4Q3Ln+Q/J3ynPpId5T/Ili2mAIHhP6Afaz/HjNw/
        qHVJjoOo2z8AGLl1IlrgP0YeYFup6NQ/buMZHORK1j9cuO/hO9HmPwiu3qxS/eM/6OK25jbl3z/3
        OBQjE2njP0DAS5ynwOM/QTcKR8H+2D9P4P6lRxvUP5rFBcX43Ns/h0LhaAqc4D8Lc83m7EjcP7OF
        mTbEjeE/OKTRXHQv4z8/6n6nJDjhP9OrTecki9c/enXHmCLE3T+o/phqv4nmPyf6vBFIO+E/aG5T
        8bJh4z+8zf944+DhPycTDoX8deI/hD4x7jm85D/I7xQsP8LdP13ANfo0FOU/cLjINNXn3z+Mxv78
        Kp7WP5oTdEfhlts/o2IA0DYw4z8nOh31gn/iP7NgKpAk+90/Ex3MnXr73D/EtgTCECPRP9zAycoK
        WeE/izRJmZiu0D8W3CdGqdvjP+hgepNdq9Y/safLnJdE4T+J0MS3l5jZP49iSlEY0+Y/U17lddm5
        4z+cb76YrRDgP44/siU0aNc/ixxORGmW2D/YBzW4Me/kPypP333Px9c/vktsIa5i6T/wIGLkLgfi
        P8JosC0VcuI/8C5hkgtU5z9RmIoyr2viPwbDthT9K+E/I+tf8Wl94z8AWsKJxYXlPw==
    y_true: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 398
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
  test_scores:
    accuracy: 0.41959798994974873
    f1: 0.03347280334728033
    pr_auc: 0.03764066162663468
    precision: 0.017241379310344827
    recall: 0.5714285714285714
    roc_auc: 0.5601023017902812
