config:
  batch_size: 32
  data_paths:
  - test_datasets/jain/canonical/VH_only_jain_test_PARITY_86.csv
  device: mps
  label_column: label
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc
  - pr_auc
  model_paths:
  - models/boughter_vh_esm2_650m_logreg.pkl
  output_dir: ./test_results
  save_predictions: true
  sequence_column: sequence
dataset: VH_only_jain_test_PARITY_86
model: boughter_vh_esm2_650m_logreg
results:
  classification_report:
    '0.0':
      f1-score: 0.7090909090909091
      precision: 0.7647058823529411
      recall: 0.6610169491525424
      support: 59.0
    '1.0':
      f1-score: 0.4838709677419355
      precision: 0.42857142857142855
      recall: 0.5555555555555556
      support: 27.0
    accuracy: 0.627906976744186
    macro avg:
      f1-score: 0.5964809384164222
      precision: 0.5966386554621849
      recall: 0.608286252354049
      support: 86.0
    weighted avg:
      f1-score: 0.6383823228534407
      precision: 0.6591752980261872
      recall: 0.627906976744186
      support: 86.0
  confusion_matrix: !!python/object/apply:numpy._core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 2
      - 2
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      JwAAAAAAAAAUAAAAAAAAAAwAAAAAAAAADwAAAAAAAAA=
  predictions:
    y_pred: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 86
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAB
        AAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA
        AAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAA
        AAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAB
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA
        AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAA==
    y_proba: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 86
      - &id003 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        wZowFlWH0T9mZ/PAqDPTPzW0rsrTMOY//Z30rr261j800Wbe0yngPwA4JQc4md0/dGNQEgsV4D8v
        ACQ/BrzqPwK3e0uiH98/wrQv9imi4z9z1L1c2NPQPzXkQN+D6OE/4gOHdCu02z8/4vXwPfzVP067
        WGkTad0/2EiDfbtI0j8362PORxThP0DPaHxveug/qb+Wr+/w0T88Ta7CUTPaP0ezCHp4COM/2tdN
        z1GS4z/hhFBEBIzgP/84Ot1yhOA/0vpgDstK0T9bvSJv17LhP1kx0dwtVtk/ZqQZFXiI3j9+7ulT
        jcfVP6ChsEeL1tA/b3ZuO2Ns4T+0sof1EuLZP8c4Xkg8FdY/oVR+X5X84D8EXQWyYVriP657GRCF
        EuE/NdSX42Ze5j97SHJmjN3jP3vCksdC3eE/uc/Mjg1H4D8rmhlqDDDiPwXSoBGTgNg/KIhKbPaV
        0z92vgZCX2vePz63aSRQ39Q/8IBGd9yD1T/LNsQFh7zcP6MKW8lHR+E/i9Ug8rgI5T/Ewd+AJHzX
        Pzb3w0AbJNA/Xf5HZFAJ3D+QJ4f0F5/mP7NgY7mIhN0/kRekzits2z8lM685ipXeP5yzSi18UeI/
        iKN0W8rq1z9hmJV/lC7SP4tf3zjJmd4/tferAnZG3D/WQpKikl7jP4gYZ/CMO+U/vB0tprk74D+J
        dnXeiSjhPzvcybaSlNw/++lz+SED1j/CRn62Ua7jP4ZAt0owxNk/n7QFm+1O2j9LEESP4tfiP/sz
        rhfbut0/rr8TfuVs4j9GHTcqLIDPP8GhnYfMvtY/QiRUGeKK2j8kANK0xfDWP4O6JWRFWdk/Ysa8
        5P5i3T+oZl+ldOXiP4h20IbCC90/CL9HuZZ56D8jkFWY6b3cP5i9tb60rdo/qfPat2Wj1D82rdXs
        Fj7WPw==
    y_true: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 86
      - *id003
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8A
        AAAAAADwPwAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAA
        AAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAA
        AAAA8D8AAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAA
        AADwPwAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAA
        AAAAAAAAAAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAA
        AAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAA==
  test_scores:
    accuracy: 0.627906976744186
    f1: 0.4838709677419355
    pr_auc: 0.4662550740657045
    precision: 0.42857142857142855
    recall: 0.5555555555555556
    roc_auc: 0.6126804770872567
