config:
  batch_size: 32
  data_paths:
  - data/test/shehata/fragments/VH_only_shehata.csv
  device: cpu
  label_column: label
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc
  - pr_auc
  model_paths:
  - models/boughter_vh_esm1v_logreg.pkl
  output_dir: test_results
  save_predictions: true
  sequence_column: sequence
dataset: VH_only_shehata
results:
  boughter_vh_esm1v_logreg:
    classification_report:
      '0':
        f1-score: 0.6834170854271356
        precision: 0.9902912621359223
        recall: 0.5217391304347826
        support: 391.0
      '1':
        f1-score: 0.05025125628140704
        precision: 0.026041666666666668
        recall: 0.7142857142857143
        support: 7.0
      accuracy: 0.5251256281407035
      macro avg:
        f1-score: 0.36683417085427134
        precision: 0.5081664644012945
        recall: 0.6180124223602484
        support: 398.0
      weighted avg:
        f1-score: 0.6722810030049746
        precision: 0.9733320983965134
        recall: 0.5251256281407035
        support: 398.0
    confusion_matrix: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - &id001 !!python/name:numpy.ndarray ''
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 2
        - 2
      - &id002 !!python/object/apply:numpy.dtype
        args:
        - i8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        zAAAAAAAAAC7AAAAAAAAAAIAAAAAAAAABQAAAAAAAAA=
    predictions:
      y_pred: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 398
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB
          AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
          AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA
          AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAB
          AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAA
          AAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAA
          AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA
          AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAB
          AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
          AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA
          AAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA
          AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA
          AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB
          AAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
          AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAA
          AAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB
          AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
          AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAA
          AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAA
          AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAA
          AAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAA
          AAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
          AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA
          AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEA
          AAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA
          AAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAA
          AAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAA
          AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
          AQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAA
          AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAA
          AAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==
      y_proba: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 398
        - !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          oT+sCY9p1T82mdN0/FHPP3phIAh/+Mc/LQjd/iTIzz+hLv0Old7iP3YYFSdqz+U/K+6xgxe+uD/8
          HiPzdP3iP159xgSvi+E/Y0CfzLEMvz+G/gq64RXnP8ytqS7GFt0/GImsgRUF6T8guegU1XbQP6zJ
          1+dCINA/BfOThdva6j/bX+r33OLhP1AcYaw6Nt4/WYfkKQz94T+oExs3WtndP0ETw/OV8eA/RmS2
          6yB63T+rIeJWL7bdP43uwcLJbOY/Sy86kb1t0j/rdOUqx7rVP/GFn1YJ8dw/zTrx8AGv2j+vLMbE
          qLLQP2QSjMghkMk/veTzSFfd2D+H8mMkVKS7PxZ2iyjHPOU/7Vaor4D42D8m8r2dDeniP0TCZ2mD
          5N8/jL0PgFA86D9W4fExujPWP42No0KVst4/PwLDbzr+5T+szxofU97bPwDqyK0bA+U/qzPnJ3q2
          4T9TJ7+L5AfXPznplwzaYcI/kaKyZeFb4j/eNWAmj8TjP++FL7wRud8/Aa4M0x565j/tMtVumTXT
          PwE/lc8dedQ/7wXimwMJ3j/6aTj1BonaP5/7Pk29luc/Cc+13BTJ4T+my5g/yhvTP5jlI1a5XOo/
          pEfUdWym1T/UiPbh0FTgP6SJSvTgatQ/IiUTX5kq4D8eBMB4ECfSP4M0GuA669Y/Whklu7d64D/9
          44o+QinkP95KooOQJ+s/NW3K1Kbs4j9FI0/UtRzYP7BULbJV3+Q/F54a7dvD4D+ysEmovMzWP1/3
          trU+Lec/RvEYoBR23D/EZCpYDsnGP529GDV3f9U/iolZ3/KI5j+imVCElWHqP16V4/f1rc8/AR89
          fcjR5T9+JTp29xjUP7qVeR6I4tQ/41TtCf4I5j+PjomBlJzoP8UMTSsvLeY/hx4QpL2R6T8q6IE3
          AYfkP/PVJeejhOE/Z42OpmrC2D/vXrITHIzpP7/UuDzoXdo/IgRx6/w45z9gHI/s82jlP5k57bGP
          DeE/7ZNpAwp/0z9VlO0bwn7kP8t5dQQay98/wo/bX/aYzz+yi99yZMXaP61Qip0pZuM/gV2PPM4S
          5T8HyusVenfVP8lqTEGsfNw/2H3RiM3v2D9K1NoBelztPyxMjRaV2ug/NmxonBzP1j+PGtUMzXnF
          P/Z9APjZ2uI/dxwDwvkh4T+nq8OIc/TTP/EaSNu32NA/oXU/hIQZ5D+30J01CdHrPwlw/OTn1uc/
          4OgymjTp4D80KvKJPEPXPy24V5cuJ+k/DeMrhoYQ2j8zW7tmOS3iPwtM78/g2d0/O1S8Z/H95z/D
          eiYHDufoP5wTcnTQReg/hl6r+krA6T9Gpnkm3CXmP70idNjJP9s/T9edTMtfwj+5MWGbRXXYPzNx
          CJmpZ+Y/K4H/l4m86D+lxeoZOTrGPzgSTVp4oec/qmDdIWK96z8lPdItTc/aP5EovOtmI9s/uWMK
          CSUy6D9Q54B3hwjgPySkw3qAE+E/gO9ZhY0d0T9XWJDwO6zdPzsM3Q9xg+M/EmLqq8aCxT9Bm/S2
          saXrP5FafMmvBeU/WnkfkU5F4j+FCG3SB2nnP2D+WVAvuNg/+Gr6f1bszD+NTrzHmgLSP+tJG+mx
          fuE/agoA9cGNxz9e4WGkpbbDP/e2YG3+H+E//y6h46tj3z9xKB956Oa/P/cu4mCdfL0/nHzZjh13
          2D/N8YPNgmvmP2pec3j9PN8/HW/HdY5f0j9DbfjlDgHkP461XUK6YdQ/9SmNWLgA1j+QF969Z7PI
          P41zYvXckcs/nQyQ9SPj2D/W+vZsxw7UP0Ueg7z4FOk/Gx1uvjmF0j9WDEOCw4/aPydiIS/avOM/
          R7JBXk/P6j9JGbO3qB/RP+vHehstL+A/nAhROiMX6j8aeej32H/iP8WkmpSkcN4/1WOkLOw+xT/g
          KawE7YvhP85rzHOU9Nw/S/aVdGpr4j+kKMtsekTSP42hkC7sKOo/EtxcviU20z+MFZJ297PQPych
          Y8Ew/90//yYS8mnh6D+iGQ7q/ObgP5fmIQbzCtY/R+NanlJ60j+Y6CCNcTPPP0A0uM3jmec/WONM
          U+2M4T8tSOANkg/SPzGkMifXrdo/5AW8N6p52j9GFKtYbCjjPxr67Qa+3Ng/UTTcbikr1j+qOlJd
          yaLSPzQWkkOiKuM/m5xstuV63z9vjtdSUuTlP507jEv3xtU/IkOpreJM1D8ggyoN/FXoP2amRskx
          iMM/jHUeskPf6z9gvmFzBTXQP3tdY1C1hMk/ZrhR0u4N2T/VJqYGSXfoP5vKpQKkreg/yXfhHdeH
          4z/NOf/EauzjP23JuXgfvus/V9PmoFV43T/N/2tpPFfSP563tA+j7c8/5bWnV+wU3D8NbFNixhPe
          P+5Z98nrzuo/4iJkqLFHzT/+bud1nOXiP5TBjspkycw/nm1yBwOu1z9eCZD72PXSP6Xc1JWZvNM/
          cBT7o7094D8bkC3w77jIPw6Ba5ni+9s/iNY3S3yA4T/4J5efaJrTPxv82bb8COE/N//AnjVZzj9C
          rhWHP4roPyGHOn4Iaes/2VWwqwiQ6z9qBYw4fdjEP+XFwVB5DuA/FCq49JuT3D9tBJCpQl7eP9ax
          1LEEV+I/4Urp1Q+F4z93fMRDQ/HDP0y8UB4+Sts/1B51qS6X2z/cY7xlDNThP9qDHcNx9r4/KzRu
          +Cqx4z8+x3CKAX/FP9x7E7g/RuY/a3YKig0bzj9ZtgIxJynnP20KgL0TQd8/v4bZvZG71j87kleh
          1X7dP/nRizjWuMw/vrc7TDiXxT/xSDGXzPbYPx0hdiD+9uc/UUJJOAWW0T+l9SOuznHqP7QE/sY/
          9eY/aLb+rlbQ5j9yKzVwxoPRP7AY3+yXntY/3GjxgMKq2z/JzezI4enTP5KkWjxPkdM/bRlAxTbh
          4j9G/+fL6hPRP+IYfyhA/eo/Vx2rbxN25D+w5xcosA3OP7IwXmKcTdw/APpE2Wa06j92iDuDugzq
          P9dPEI2jW84/WBzPMnga5z/myRsYktjlP1hDgsJq1Ow/XCW0y5z96j88FDcOY+XsP0BSWT7zjdk/
          DofNppc+5j97qOJ0g0jWP8btL4y6sd4/4a6qmwqv4T/VrVIXEiXlP1Kz+O5Qs+I/hQ6boI7J5T9U
          qWRlo2rVP6r4U+qQbuY/axESQxTZ6j9WWTGSQo/aP7oTGLgLmdc/gJH0xHVf5T/ypZjgjDLWP2Ec
          IxhktOc/Nqi1qXSw4T89UF1XXEXnPx5tErHPYO4/5gJcNjlp2j+avVtFh+nRP0LdjOzhZuM/mxCa
          s0cF6T8xN2ZieRfmP3aUd7ljfeI/hQwXniP36j9IPCMWPo7dP8Iq3kz/5eY/7kQmHL8K2D9lyfxP
          AXHeP2vz5fXqhOY/C32d45TZ7D8vdxqx7BTrP2Ra1IdaF9E/h2DegXjo6T8T/FDM8OPLP7qhD/mX
          D+g/1nMmIGzZ0j8rtsp0Y17kP9ylTsReTeU/4g5/xTF+5T/I3RwBRt/jP8sLSMnrn9I/Z1EB/gFc
          4j9RG5EOZJXQP1zpiK7/aeU/rEVXvUQM3T8hTL9ej3HnP1ygqtUEe90/FVEWnPqZ4z9U4RaKA5DT
          P+d8uQQPf90/hUeDd5xk1D8ToK/XtF3jP1RSqhAGlOU//cuzL1Vb5T8gnGzxGb3mP8uMsl5Glcg/
          JSol6yRS4T8VGcIS+angP66nk58I9s8/CoGo1gbqzT/ZqK2SU03qPwccKiMUhuw/HXtBu+To0z8n
          B/dc9sbWP1Te4cR84+Y/xZA/ej1+4z/QuQ9RT8vRP/nqxrXRE9w/u9oKBFtL4z+JMiV8y43UPymj
          f5jDCNc/NOlYT9cq2j9w0XcStJfkP29r7WIajsg/4kM/+hovzz+A3kmdM8jkP1fHPzpprd0/CA7I
          uRIq0j8KT/z00MfYPzBxZQR6kN4/3zmAV7Ch4T/+vidXMpHaP7iVCgUcxd0/brUf0+mR4D/rw4tv
          XTG9P1NDPqcSa9I/d2Ph6Zfb4T+ign/Mi5LkP4iHwBQCotw/eH7Bv2IU4D9UjUkz+u7JPzzYC5il
          XuU/0imWXFVRyT/T5oQgnW3kP6K9JeocpsM/ym3DQetH4j/lK0dis9fVPwE3JbaFh+Q/r2MGx5bb
          3D808bZgEbbUPzPROmQrt8Y/puvZvHQ73D9Q2Myn8PvjP9hAVNRjotQ/xmcaPbC77T+G0fA9/9Pi
          PwfkieMZ+dE/Z9xrSVM25D+Tobo4RiTiP5jk0M1IO+M/damWcU3F5z+pA05dCInkPw==
      y_true: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 398
        - *id002
        - false
        - !!binary |
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    test_scores:
      accuracy: 0.5251256281407035
      f1: 0.05025125628140704
      pr_auc: 0.09875968102038822
      precision: 0.026041666666666668
      recall: 0.7142857142857143
      roc_auc: 0.6667884545122397
